language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2

gemfile:
  - Gemfile
  - gemfiles/Gemfile.rails-edge
  - gemfiles/Gemfile.rails-4.1
  - gemfiles/Gemfile.rails-4.0
  - gemfiles/Gemfile.rails-3.2

matrix:
  include:
    - rvm: 1.9.3
      gemfile: gemfiles/Gemfile.rails-3.1
