language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.9
  - 2.2.5
  - 2.3.1

gemfile:
  - Gemfile
  - gemfiles/Gemfile.rails-4.2
  - gemfiles/Gemfile.rails-4.1
  - gemfiles/Gemfile.rails-4.0
  - gemfiles/Gemfile.rails-3.2

matrix:
  include:
    - rvm: 1.9.3
      gemfile: gemfiles/Gemfile.rails-3.1
    - rvm: 2.2
      gemfile: gemfiles/Gemfile.rails-edge
  exclude:
    - rvm: 1.9.3
      gemfile: Gemfile
    - rvm: 2.0.0
      gemfile: Gemfile
    - rvm: 2.1.9
      gemfile: Gemfile
  allow_failures:
    - gemfile: gemfiles/Gemfile.rails-edge
